# 1. Series 的创建

In [1]:
# series 的创建
import pandas as pd
import numpy as np

s = pd.Series([1,2,3,4,5])
print(s)

#自定义索引
s = pd.Series([10,2,4,5,6], index=['A','B','C','D','E'])
print(s)
#定义name
s = pd.Series([10,2,4,5,6], index=['A','B','C','D','E'], name='月份')
print(s)

#通过字典来创建
s = pd.Series({'a':1,'b':2,'c':3,'d':4,'e':5},name= "月份")
print(s)
s1 = pd.Series(s, index=['a','c'])
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64
A    10
B     2
C     4
D     5
E     6
dtype: int64
A    10
B     2
C     4
D     5
E     6
Name: 月份, dtype: int64
a    1
b    2
c    3
d    4
e    5
Name: 月份, dtype: int64
a    1
c    3
Name: 月份, dtype: int64

# 2. Series 的属性

In [26]:
print(s)
print(s.index)  #索引
print(s.values)
print(s.shape, s.ndim, s.size)
print(s.dtype,     s.name)
print('-----------')
print(s.loc['b'])   #显式索引
print(s.loc['a':'c'])
print(s.iloc[1])    #隐式索引
print(s.at['b'])

a    1
b    2
c    3
d    4
e    5
Name: 月份, dtype: int64
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[1 2 3 4 5]
(5,) 1 5
int64 月份
-----------
2
a    1
b    2
c    3
Name: 月份, dtype: int64
2
2

In [ ]:
#访问数据
print(s['a'])
print(s)
print(s[s<3])
print(s.head())     #前5
print(s.tail())     #后5

1
a    1
b    2
c    3
d    4
e    5
Name: 月份, dtype: int64
a    1
b    2
Name: 月份, dtype: int64
a    1
b    2
c    3
d    4
e    5
Name: 月份, dtype: int64
a    1
b    2
c    3
d    4
e    5
Name: 月份, dtype: int64

# 3. Series 常见函数的学习

In [ ]:
s = pd.Series([10,2,np.nan,None,3,4,5],
              index=["A","B","C","D","E","F","G"],
              name='test')
print(s)
s.head(2)
s.tail(6)
print('----------')
# 查看所有的描述性信息
print(s.describe())    #只统计有意义的数

#获取元素个数(忽略缺失值)
print(s.count() )  
#获取索引
print(s.keys())
print(s.index)

print(s.isna())     #检测缺失
print('-------------')  #检测元素是否存在
print(s.isin([4]))

A    10.0
B     2.0
C     NaN
D     NaN
E     3.0
F     4.0
G     5.0
Name: test, dtype: float64
----------
count     5.000000
mean      4.800000
std       3.114482
min       2.000000
25%       3.000000
50%       4.000000
75%       5.000000
max      10.000000
Name: test, dtype: float64
5
Index(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='object')
Index(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='object')
A    False
B    False
C     True
D     True
E    False
F    False
G    False
Name: test, dtype: bool
-------------
A    False
B    False
C    False
D    False
E    False
F     True
G    False
Name: test, dtype: bool

In [ ]:
#项目1
import pandas as pd
import numpy as np
np.random.seed(20)
values = np.random.randint(50,101,10)
indexes = []
for i in range(1,11):
    indexes.append('学生'+str(i))
scores = pd.Series(values,indexes)
print(scores)
print("平均分：", scores.mean())
print("最高分：", scores.max())
print("最低分：", scores.min())
#高于平均分的学生人数
mean = scores.mean()
scores[scores>mean]
print("高于平均分的学生人数：",len(scores[scores>mean]))
print("高于平均分的学生人数：",scores[scores>mean].count())

学生1     85
学生2     76
学生3     65
学生4     81
学生5     78
学生6     76
学生7     59
学生8     70
学生9     61
学生10    72
dtype: int32
平均分： 72.3
最高分： 85
最低分： 59
高于平均分的学生人数： 5
高于平均分的学生人数： 5

# 1. DataFrame 的创建

In [11]:
import pandas as pd
import numpy as np


#通过series来构建
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([6,7,8,9,10])
df = pd.DataFrame({"第一列":s1,"第二列":s2})
df = pd.DataFrame(
    {
    "id":[1,2,3,4,5],
    "name":["tom", "mike", "jack", "bob", "alice"],
    "age":[15,17,16,14,18],
    "score":[60.5,80,46,89,76]
    },index=[1,2,3,4,5],columns=["name","age","score"]
)
df

    name  age  score
1    tom   15   60.5
2   mike   17   80.0
3   jack   16   46.0
4    bob   14   89.0
5  alice   18   76.0

# 2. DataFrame 的属性

In [ ]:
print("行索引：")
print(df.index)
print("列标签：")
print(df.columns)
print("值：")
print(df.values)

print("维度：",df.ndim)
print("形状：",df.shape)
print("数据类型:")
print(df.dtypes)

#行列转置
print(df.T)
print(df.T.index)
print("----------")

行索引：
Index([1, 2, 3, 4, 5], dtype='int64')
列标签：
Index(['name', 'age', 'score'], dtype='object')
值：
[['tom' 15 60.5]
 ['mike' 17 80.0]
 ['jack' 16 46.0]
 ['bob' 14 89.0]
 ['alice' 18 76.0]]
维度： 2
形状： (5, 3)
数据类型:
name      object
age        int64
score    float64
dtype: object
          1     2     3     4      5
name    tom  mike  jack   bob  alice
age      15    17    16    14     18
score  60.5  80.0  46.0  89.0   76.0
Index(['name', 'age', 'score'], dtype='object')
----------
name      bob
age        14
score    89.0
Name: 4, dtype: object
name      bob
age        14
score    89.0
Name: 4, dtype: object
1      tom
2     mike
3     jack
4      bob
5    alice
Name: name, dtype: object

In [32]:
#获取元素 loc iloc at iat 
print(df)
print("---------")
#某行
print(df.loc[4])    #index
print(df.iloc[3])   #序号
#某列
print(df.loc[:,'name']) 
print(df.iloc[:,0])

    name  age  score
1    tom   15   60.5
2   mike   17   80.0
3   jack   16   46.0
4    bob   14   89.0
5  alice   18   76.0
---------
name      bob
age        14
score    89.0
Name: 4, dtype: object
name      bob
age        14
score    89.0
Name: 4, dtype: object
1      tom
2     mike
3     jack
4      bob
5    alice
Name: name, dtype: object
1      tom
2     mike
3     jack
4      bob
5    alice
Name: name, dtype: object

In [36]:
print(df)
#当个元素
print(df.at[3,"score"])
print(df.iat[2,2])

    name  age  score
1    tom   15   60.5
2   mike   17   80.0
3   jack   16   46.0
4    bob   14   89.0
5  alice   18   76.0
46.0
46.0

In [ ]:
# 获取单列数据
print(df)
print(df["name"])
print(df.name)
print(df[["name"]]) #还是dataframe

    name  age  score
1    tom   15   60.5
2   mike   17   80.0
3   jack   16   46.0
4    bob   14   89.0
5  alice   18   76.0
1      tom
2     mike
3     jack
4      bob
5    alice
Name: name, dtype: object
1      tom
2     mike
3     jack
4      bob
5    alice
Name: name, dtype: object
    name
1    tom
2   mike
3   jack
4    bob
5  alice

In [47]:
#查看部分数据
print(df.head(3))
print(df.tail(4))
#使用布尔索引筛选数据
df[(df.score>70) & (df.age<15)]

   name  age  score
1   tom   15   60.5
2  mike   17   80.0
3  jack   16   46.0
    name  age  score
2   mike   17   80.0
3   jack   16   46.0
4    bob   14   89.0
5  alice   18   76.0

  name  age  score
4  bob   14   89.0

In [48]:
#随机抽样
df.sample(3)

    name  age  score
5  alice   18   76.0
1    tom   15   60.5
4    bob   14   89.0

# 3. DateFrame 的常用方法

In [54]:
print(df)
print(df.head(1))
print(df.tail(1))
print("---------")
print(df.isin(['jack',46]))

    name  age  score
1    tom   15   60.5
2   mike   17   80.0
3   jack   16   46.0
4    bob   14   89.0
5  alice   18   76.0
  name  age  score
1  tom   15   60.5
    name  age  score
5  alice   18   76.0
---------
    name    age  score
1  False  False  False
2  False  False  False
3   True  False   True
4  False  False  False
5  False  False  False

In [ ]:
print(df.isna())

print(df["score"].sum())
print(df.score.max())
print(df.age.min())
print(df.score.mean())      #平均数
print(df.score.median())    #中位数
print(df.score.mode())      #众数

    name    age  score
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
351.5
89.0
14
70.3
76.0
0    46.0
1    60.5
2    76.0
3    80.0
4    89.0
Name: score, dtype: float64

In [ ]:
print(df.score.std())
print(df.score.var())
print(df.score.quantile(0.25))  #分位数
print(df.describe())
print(df.count())   #非缺失值的个数
print(df.value_counts())    #出现的次数/频率
print(df.drop_duplicates()) #去重

17.049926686059386
290.7
60.5
             age      score
count   5.000000   5.000000
mean   16.000000  70.300000
std     1.581139  17.049927
min    14.000000  46.000000
25%    15.000000  60.500000
50%    16.000000  76.000000
75%    17.000000  80.000000
max    18.000000  89.000000
name     5
age      5
score    5
dtype: int64
name   age  score
alice  18   76.0     1
bob    14   89.0     1
jack   16   46.0     1
mike   17   80.0     1
tom    15   60.5     1
Name: count, dtype: int64
    name  age  score
1    tom   15   60.5
2   mike   17   80.0
3   jack   16   46.0
4    bob   14   89.0
5  alice   18   76.0
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [74]:
print(df.duplicated(subset= "age")) #查看是否重复
df.sample() #随机抽样
print(df.replace(15,20))

1    False
2    False
3    False
4    False
5    False
dtype: bool
    name  age  score
1    tom   20   60.5
2   mike   17   80.0
3   jack   16   46.0
4    bob   14   89.0
5  alice   18   76.0

In [76]:
print(df)
print(df.cumsum())

    name  age  score
1    tom   15   60.5
2   mike   17   80.0
3   jack   16   46.0
4    bob   14   89.0
5  alice   18   76.0
                  name  age  score
1                  tom   15   60.5
2              tommike   32  140.5
3          tommikejack   48  186.5
4       tommikejackbob   62  275.5
5  tommikejackbobalice   80  351.5

In [81]:
print(df.sort_index(ascending=False))
print(df.sort_values(by= ["score","age"],ascending=[False,True]))

    name  age  score
5  alice   18   76.0
4    bob   14   89.0
3   jack   16   46.0
2   mike   17   80.0
1    tom   15   60.5
    name  age  score
4    bob   14   89.0
2   mike   17   80.0
5  alice   18   76.0
1    tom   15   60.5
3   jack   16   46.0

In [ ]:
#项目
import pandas as pd
data = {
    "产品名称":["A","B","C","D"],
    "单价":[100,150,200,120],
    "销量":[50,30,20,40]
}

df = pd.DataFrame(data)
df["总销售额"] = df["单价"]*df["销量"]
df.nlargest(1,columns=["总销售额"])     #1表示取1个
df.sort_values(["总销售额"],ascending=False)

  产品名称   单价  销量  总销售额
0    A  100  50  5000
3    D  120  40  4800
1    B  150  30  4500
2    C  200  20  4000